---

- name: neighbors testing
  hosts: Spines,Leafs
  connection: local
  gather_facts: no

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"

  tasks:

    - name: "Get LLDP neighbors"
      nxos_get_neighbors:
        type= lldp 
        host={{ ansible_host }}

    - debug: var=neighbors

    - name: "Get CDP neighbors"
      nxos_get_neighbors: type=cdp host={{ ansible_host }}

    - debug: var=neighbors
