---
-
  connection: local
  gather_facts: false
  hosts: Leafs

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"

  tasks:

    - name : Find mac address on the vxlan fabric
      nxos_command:
        commands:
#          - show l2route evpn mac-ip all
          - show l2route evpn mac-ip all | g 0050.7966.680c | g Local
#          - show l2route evpn mac all
          - show l2route evpn mac all | g 0050.7966.680c | g Local
#        waitfor:
#          - result[0] contains 'Local'
        host: "{{ ansible_host }}"
        provider: "{{ nxos_provider }}"
      register: result

    - name: print results
      debug:
        var: result.stdout_lines





