---
- name: Leaf Switch - Port Provisioning
  hosts: Leafs
  gather_facts: no

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"

  tasks:

    - name: Configure TRunk Interafce to Server on Leaf Switch
      nxos_config:
        lines:
          - description Connected-tO-srver1
          - no shutdown
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20
        parents: interface Ethernet1/10
        provider: "{{ nxos_provider }}"

    - name: Configure Access-port to Server on Leaf Switch                  
      nxos_config:
        lines:
          - description Connected-tO-srver2      
          - no shutdown
          - switchport mode access
          - switchport access vlan 20
        parents: interface Ethernet1/11
        provider: "{{ nxos_provider }}"



