---
- hosts: Spines,Leafs
  connection: local
  gather_facts: no

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"

  tasks:

    - name: ____Test Connection to Spines and Leafs____
      ping: 
