---
- hosts: Spines,Leafs
  connection: local
  gather_facts: no

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"

  tasks:

    - name: ____Test Uptime to Spines and Leafs____
      command: ansible all -m command -u root --args "uptime" --one-line
