---
- name: Backup des configurations
  hosts: Spines,Leafs
  gather_facts: no

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"

  tasks:

    - name: run show running-config on remote devices
      nxos_command:
        commands: show run
        provider: "{{ nxos_provider }}"
      register: config

    - name: Set current date and time to file
      set_fact: temp="{{lookup('pipe','date \"+%Y-%m-%d_%H:%M\"')}}"


    - name: save output to /etc/ansible/CFGS
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "/etc/ansible/CFGS/{{ inventory_hostname }}_running-config_{{temp}}.txt"


