---
- name: Check Running VS Startup Configuraions Diff
  hosts: Leafs
  gather_facts: no
 
  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ ansible_host }}"
 
  tasks:
    - name: diff against the startup config
      nxos_config:
        diff_against: startup
        provider: "{{ nxos_provider }}"
      register: test_diff

#    - name: print results
#      debug:
#        var: test_diff.stdout_lines
